set_property SRC_FILE_INFO {cfile:d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc rfile:../../../daq2_zcu102.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:i_system_wrapper/system_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/constrs_1/new/system_constr.xdc rfile:../../../daq2_zcu102.srcs/constrs_1/new/system_constr.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/adi_9234/ad9234-6-Laser/zcu102_system_constr.xdc rfile:../../../zcu102_system_constr.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:D:/adi_9234/ad9234-6-Laser/system_constr.xdc rfile:../../../system_constr.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc rfile:../../../daq2_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc id:5 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets rx_sysref]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AN14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[0]}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AP14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[1]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AM14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[2]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AN13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[3]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AN12 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[4]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AP12 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[5]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AL13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[6]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[7]}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[8]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[9]}]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[10]}]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[11]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_i[12]}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[0]}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[1]}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[2]}]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[3]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ15 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[4]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH13 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[5]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH14 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[6]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AL12 IOSTANDARD LVCMOS33} [get_ports {gpio_bd_o[7]}]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports spi1_clk]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports spi1_sdio]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports status1]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports spi1_csn_0]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports clk_resetn]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports port_sysref]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports port_lmfc_clk]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports port_lmfc_edge]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports port_start1]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports port_rx_out_clk]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AL8 IOSTANDARD DIFF_SSTL12} [get_ports port_clk_in1_p]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AL7 IOSTANDARD DIFF_SSTL12} [get_ports port_clk_in1_n]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA2 IOSTANDARD LVDS} [get_ports rx_sync_p]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVDS} [get_ports rx_sync_n]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC2 IOSTANDARD LVCMOS18} [get_ports spi_csn_adc]
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB4 IOSTANDARD LVCMOS18} [get_ports spi_clk]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC4 IOSTANDARD LVCMOS18} [get_ports fmc_spi_mosi]
set_property src_info {type:XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS18} [get_ports fmc_spi_miso]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V1 IOSTANDARD LVCMOS18} [get_ports adc_pd]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS18} [get_ports adc_fda]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD LVCMOS18} [get_ports adc_fdb]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_COMMON_X1Y2 [get_cells -hierarchical -filter {NAME =~ *i_ibufds_rx_ref_clk}]
set_property src_info {type:XDC file:4 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2} [get_ports {rx_data_p[0]}]
set_property src_info {type:XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K1} [get_ports {rx_data_n[0]}]
set_property src_info {type:XDC file:4 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F2} [get_ports {rx_data_p[1]}]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F1} [get_ports {rx_data_n[1]}]
set_property src_info {type:XDC file:4 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H2} [get_ports {rx_data_p[2]}]
set_property src_info {type:XDC file:4 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H1} [get_ports {rx_data_n[2]}]
set_property src_info {type:XDC file:4 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J4} [get_ports {rx_data_p[3]}]
set_property src_info {type:XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J3} [get_ports {rx_data_n[3]}]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X1Y8 [get_cells -hierarchical -filter {NAME =~ *util_daq2_xcvr/inst/i_xch_0/i_gthe4_channel}]
set_property src_info {type:XDC file:4 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X1Y11 [get_cells -hierarchical -filter {NAME =~ *util_daq2_xcvr/inst/i_xch_1/i_gthe4_channel}]
set_property src_info {type:XDC file:4 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X1Y10 [get_cells -hierarchical -filter {NAME =~ *util_daq2_xcvr/inst/i_xch_2/i_gthe4_channel}]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X1Y9 [get_cells -hierarchical -filter {NAME =~ *util_daq2_xcvr/inst/i_xch_3/i_gthe4_channel}]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA7} [get_ports rx_sysref_p]
set_property src_info {type:XDC file:4 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA6} [get_ports rx_sysref_n]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G8} [get_ports rx_ref_clk_p]
set_property src_info {type:XDC file:4 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G7} [get_ports rx_ref_clk_n]
set_property src_info {type:SCOPED_XDC file:5 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/i_cdc_status/cdc_hold_reg[*]/C}] -to [get_pins {i_up_rx/i_cdc_status/out_data_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/i_cdc_cfg/cdc_hold_reg[*]/C}] -to [get_pins {i_up_rx/i_cdc_cfg/out_data_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:5 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]] -to [get_pins {i_up_rx/*i_up_rx_lane/up_status_latency_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/gen_lane[*].i_up_rx_lane/i_ilas_mem/mem_reg_*/*/CLK}] -to [get_pins {i_up_rx/gen_lane[*].i_up_rx_lane/i_ilas_mem/up_rdata_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_common/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_cfg_*_reg*/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:5 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:5 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_sysref/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
