# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -ruleid {4}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -ruleid {5}  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -ruleid {9}  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/adi/ad9234_1/library/axi_ad9680/axi_ad9680.cache/wt [current_project]
set_property parent.project_path D:/adi/ad9234_1/library/axi_ad9680/axi_ad9680.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/adi/ad9234_1/library [current_project]
set_property ip_output_repo d:/adi/ad9234_1/library/axi_ad9680/axi_ad9680.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/adi/ad9234_1/library/axi_ad9680/axi_ad9680.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top axi_ad9680 -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_ad9680.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_ad9680_utilization_synth.rpt -pb axi_ad9680_utilization_synth.pb"
