#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Sep 19 20:50:38 +0800 2018
# SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 zynq_ultra_ps_e_vip_v1_0_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 xlconcat_v2_1_1 xlconstant_v1_1_3 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_15 fifo_generator_v13_2_1 axi_data_fifo_v2_1_14 axi_crossbar_v2_1_16 axi_protocol_converter_v2_1_15 axi_clock_converter_v2_1_14 blk_mem_gen_v8_4_1 axi_dwidth_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_0/sim/system_sys_ps8_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_spi0_csn_concat_0/sim/system_spi0_csn_concat_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi0_ss_i_n_VCC_0/sim/system_sys_ps8_emio_spi0_ss_i_n_VCC_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi0_sclk_i_GND_0/sim/system_sys_ps8_emio_spi0_sclk_i_GND_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi0_s_i_GND_0/sim/system_sys_ps8_emio_spi0_s_i_GND_0.v" \
    "$ref_dir/../../../bd/system/ip/system_spi1_csn_concat_0/sim/system_spi1_csn_concat_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi1_ss_i_n_VCC_0/sim/system_sys_ps8_emio_spi1_ss_i_n_VCC_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi1_sclk_i_GND_0/sim/system_sys_ps8_emio_spi1_sclk_i_GND_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi1_s_i_GND_0/sim/system_sys_ps8_emio_spi1_s_i_GND_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_0_0/sim/system_sys_concat_intc_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_1_0/sim/system_sys_concat_intc_1_0.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/hdl/library/common/ad_axis_inf_rx.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/hdl/library/common/ad_mem_asym.v" \
    "$ref_dir/../../../bd/system/ipshared/b072/util_adcfifo.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_fifo_0/sim/system_axi_ad9680_fifo_0.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_es.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_mdrp.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_mstatus.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr_up.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_axi.v" \
    "$ref_dir/../../../bd/system/ipshared/8aa1/axi_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_xcvr_0/sim/system_axi_ad9680_xcvr_0.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/ad_datafmt.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc_core.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc_deframer.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc_pnmon.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc_regmap.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/ad_pnmon.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/ad_rst.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/ad_xcvr_rx_if.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_adc_channel.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_adc_common.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_clock_mon.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/hdl/library/common/up_xfer_status.v" \
    "$ref_dir/../../../bd/system/ipshared/419f/ad_ip_jesd204_tpl_adc.v" \
    "$ref_dir/../../../bd/system/ipshared/70d6/axi_ad9680.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_core_0/sim/system_axi_ad9680_core_0.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack_dsf.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack_mux.v" \
    "$ref_dir/../../../bd/system/ipshared/2884/util_cpack.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_cpack_0/sim/system_axi_ad9680_cpack_0.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_bits.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_data.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_event.v" \
    "$ref_dir/../../../bd/system/ipshared/fb52/sync_gray.v" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/hdl/library/common/ad_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/address_gray_pipelined.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/address_sync.v" \
    "$ref_dir/../../../bd/system/ipshared/0d03/util_axis_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_dma_0/sim/system_axi_ad9680_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/225a/2d_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/address_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_burst_memory.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_regmap.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_regmap_request.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_reset_manager.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_resize_dest.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_resize_src.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/data_mover.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/dest_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/request_arb.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/request_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/response_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/response_handler.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/splitter.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/src_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/225a/axi_dmac.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_dma_0/sim/system_axi_ad9680_dma_0.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr_xch.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr_xcm.v" \
    "$ref_dir/../../../bd/system/ipshared/bdee/util_adxcvr.v" \
    "$ref_dir/../../../bd/system/ip/system_util_daq2_xcvr_0/sim/system_util_daq2_xcvr_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9680_jesd_rstgen_0/sim/system_axi_ad9680_jesd_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/ipshared/a6ac/jesd204_up_common.v" \
    "$ref_dir/../../../bd/system/ipshared/a6ac/jesd204_up_sysref.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_ilas_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/jesd204_up_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/4b85/axi_jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_axi_0/sim/system_rx_axi_0.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_eof_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_lmfc.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/jesd204_scrambler.v" \
    "$ref_dir/../../../bd/system/ipshared/c919/pipeline_stage.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/align_mux.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/elastic_buffer.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_ilas_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_lane_latency_monitor.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_cgs.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx_lane.v" \
    "$ref_dir/../../../bd/system/ipshared/f9c3/jesd204_rx.v" \
    "$ref_dir/../../../bd/system/ip/system_rx_0/sim/system_rx_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ila_0_0/sim/system_ila_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_start_LD_0_0/sim/system_start_LD_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
    "$ref_dir/../../../bd/system/ipshared/9b3e/sources_1/new/format_9234.v" \
    "$ref_dir/../../../bd/system/ip/system_format_9234_timestamp_0_0/sim/system_format_9234_timestamp_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps8_emio_spi1_ss_i_n_VCC_1/sim/system_sys_ps8_emio_spi1_ss_i_n_VCC_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/445f/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/1cdc/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/225a" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../daq2_zcu102.srcs/sources_1/bd/system/ipshared/82bb/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_1/sim/system_auto_us_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_0/sim/system_auto_us_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
