# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system_constr.xdc

# XDC: D:/adi_9234/ad9234-6-Laser/zcu102_system_constr.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_spi0_csn_concat_0/system_spi0_csn_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi0_csn_concat_0 || ORIG_REF_NAME==system_spi0_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi0_ss_i_n_VCC_0/system_sys_ps8_emio_spi0_ss_i_n_VCC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi0_ss_i_n_VCC_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi0_ss_i_n_VCC_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi0_sclk_i_GND_0/system_sys_ps8_emio_spi0_sclk_i_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi0_sclk_i_GND_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi0_sclk_i_GND_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi0_s_i_GND_0/system_sys_ps8_emio_spi0_s_i_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi0_s_i_GND_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi0_s_i_GND_0} -quiet] -quiet

# IP: bd/system/ip/system_spi1_csn_concat_0/system_spi1_csn_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi1_csn_concat_0 || ORIG_REF_NAME==system_spi1_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi1_ss_i_n_VCC_0/system_sys_ps8_emio_spi1_ss_i_n_VCC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi1_ss_i_n_VCC_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi1_ss_i_n_VCC_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi1_sclk_i_GND_0/system_sys_ps8_emio_spi1_sclk_i_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi1_sclk_i_GND_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi1_sclk_i_GND_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi1_s_i_GND_0/system_sys_ps8_emio_spi1_s_i_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi1_s_i_GND_0 || ORIG_REF_NAME==system_sys_ps8_emio_spi1_s_i_GND_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0_0/system_sys_concat_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0_0 || ORIG_REF_NAME==system_sys_concat_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_1_0/system_sys_concat_intc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_1_0 || ORIG_REF_NAME==system_sys_concat_intc_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_fifo_0/system_axi_ad9680_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_fifo_0 || ORIG_REF_NAME==system_axi_ad9680_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_xcvr_0/system_axi_ad9680_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_xcvr_0 || ORIG_REF_NAME==system_axi_ad9680_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_core_0/system_axi_ad9680_core_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_core_0 || ORIG_REF_NAME==system_axi_ad9680_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_cpack_0/system_axi_ad9680_cpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_cpack_0 || ORIG_REF_NAME==system_axi_ad9680_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_dma_0/system_axi_ad9680_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_dma_0 || ORIG_REF_NAME==system_axi_ad9680_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_util_daq2_xcvr_0/system_util_daq2_xcvr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_daq2_xcvr_0 || ORIG_REF_NAME==system_util_daq2_xcvr_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ad9680_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9680_jesd_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp3_interconnect_0/system_axi_hp3_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp3_interconnect_0 || ORIG_REF_NAME==system_axi_hp3_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_axi_0/system_rx_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] -quiet

# IP: bd/system/ip/system_rx_0/system_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] -quiet

# IP: bd/system/ip/system_ila_0_0/system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] -quiet

# IP: bd/system/ip/system_start_LD_0_0/system_start_LD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_start_LD_0_0 || ORIG_REF_NAME==system_start_LD_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_format_9234_timestamp_0_0/system_format_9234_timestamp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_format_9234_timestamp_0_0 || ORIG_REF_NAME==system_format_9234_timestamp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_emio_spi1_ss_i_n_VCC_1/system_sys_ps8_emio_spi1_ss_i_n_VCC_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_ps8_emio_spi1_ss_i_n_VCC_1 || ORIG_REF_NAME==system_sys_ps8_emio_spi1_ss_i_n_VCC_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0_ooc.xdc

# XDC: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_axi_ad9680_fifo_0/util_adcfifo_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9680_fifo_0 || ORIG_REF_NAME==system_axi_ad9680_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: hdl/library/xilinx/common/up_clock_mon_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: hdl/library/xilinx/common/up_xfer_status_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_status || ORIG_REF_NAME==up_xfer_status} -quiet] -quiet

# XDC: hdl/library/xilinx/common/ad_rst_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ad_rst || ORIG_REF_NAME==ad_rst} -quiet] -quiet

# XDC: hdl/library/xilinx/common/up_xfer_cntrl_constr.xdc
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_xfer_cntrl || ORIG_REF_NAME==up_xfer_cntrl} -quiet] -quiet

# TCL: bd/system/ip/system_axi_ad9680_dma_0/bd/bd.tcl

# XDC: bd/system/ip/system_axi_ad9680_dma_0/system_axi_ad9680_dma_0_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9680_dma_0 || ORIG_REF_NAME==system_axi_ad9680_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_util_daq2_xcvr_0/util_adxcvr_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_daq2_xcvr_0 || ORIG_REF_NAME==system_util_daq2_xcvr_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9680_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9680_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9680_jesd_rstgen_0 || ORIG_REF_NAME==system_axi_ad9680_jesd_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_axi_0 || ORIG_REF_NAME==system_rx_axi_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==up_clock_mon || ORIG_REF_NAME==up_clock_mon} -quiet] -quiet

# XDC: bd/system/ip/system_rx_0/jesd204_rx_constr.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rx_0 || ORIG_REF_NAME==system_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ila_0_0 || ORIG_REF_NAME==system_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc

# XDC: D:/adi_9234/ad9234-6-Laser/system_constr.xdc
