# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -ruleid {2}  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -ruleid {3}  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -ruleid {4}  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -ruleid {5}  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -ruleid {9}  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/adi_9234/ad9234-6-Laser/daq2_zcu102.cache/wt [current_project]
set_property parent.project_path D:/adi_9234/ad9234-6-Laser/daq2_zcu102.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.1 [current_project]
set_property ip_repo_paths {
  d:/adi/ad9234_1/library
  d:/adi_9234/waveform
  d:/adi_9234/waveform-2
} [current_project]
set_property ip_output_repo d:/adi_9234/ad9234-6-Laser/daq2_zcu102.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/adi_9234/ad9234-6-Laser/start_LD.v
  D:/adi/hdl/projects/daq2/common/daq2_spi.v
  D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/hdl/system_wrapper.v
  D:/adi_9234/ad9234-6-Laser/system_top.v
}
add_files D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_axi_ad9680_fifo_0/util_adcfifo_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/hdl/library/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/hdl/library/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/hdl/library/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/hdl/library/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_axi_ad9680_dma_0/system_axi_ad9680_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_util_daq2_xcvr_0/util_adxcvr_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_rx_0/jesd204_rx_constr.xdc]
set_property used_in_synthesis false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/constrs_1/new/system_constr.xdc
set_property used_in_implementation false [get_files D:/adi_9234/ad9234-6-Laser/daq2_zcu102.srcs/constrs_1/new/system_constr.xdc]

read_xdc D:/adi_9234/ad9234-6-Laser/zcu102_system_constr.xdc
set_property used_in_implementation false [get_files D:/adi_9234/ad9234-6-Laser/zcu102_system_constr.xdc]

read_xdc D:/adi_9234/ad9234-6-Laser/system_constr.xdc
set_property used_in_implementation false [get_files D:/adi_9234/ad9234-6-Laser/system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
